### ISSUE TITLE
Generate candidates.pkl

### ISSUE THREAD

**Issue by anil1055** [izuna385/Entity-Linking-Tutorial#16]
How can I create my candidates.pkl file for another dataset. Your candidatesgenerator.py code just load candidates.pkl in the parameters, not generator I guess. Could you help me for this problem?

Thanks

**Comment by izuna385** [comment]
Thanks for the comment. If you can get a large number of mention-entity teacher pairs like Wikipedia, you can use them for prior. See, say, [[Gillick et al.]](https://aclanthology.org/K19-1049/).
There are other methods to replace prior with other features, such as [Murty et al.](https://arxiv.org/abs/1807.05127) using string similarity, and [scispacy](https://arxiv.org/abs/1902.07669) using prior including synonyms.
